include: package:lints/core.yaml
#include: package:lints/recommended.yaml

analyzer:
  exclude:
    - doc/**
  errors:
    deprecated_member_use_from_same_package: ignore
    deprecated_member_use: ignore
    unused_element: ignore
    must_be_immutable: ignore

linter:
  rules:
    non_constant_identifier_names: false
