name: Build test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test_iOS:
    name: Test iOS on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
      - run: dart --version
      - run: flutter --version
      - run: flutter pub get
      - run: flutter pub publish --dry-run
      - run: cd example; pod install --project-directory=./ios; flutter build ios --target=./lib/main.dart --no-codesign

  test_android:
    name: Test Android on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '8.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.10.0'
      - run: dart --version
      - run: flutter --version
      - run: flutter pub get
      - run: flutter pub publish --dry-run
      - run: sudo echo "y" | sudo $ANDROID_HOME/tools/bin/sdkmanager "ndk;20.0.5594570"
      - run: cd example; flutter build apk --debug
